export const FETCH_REQUEST_LOADING = 'TEAM_FETCH_REQUEST_LOADING';
export const FETCH_REQUEST_SUCCESS = 'TEAM_FETCH_REQUEST_SUCCESS';
export const FETCH_REQUEST_FAILED = 'TEAM_FETCH_REQUEST_FAILED';
export const RESET_TEAM = 'RESET_TEAM';
